//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.commands {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.commands.ComRes", typeof(ComRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a do.
        /// </summary>
        public static string _do {
            get {
                return ResourceManager.GetString("do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lock.
        /// </summary>
        public static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aduty.
        /// </summary>
        public static string a_duty {
            get {
                return ResourceManager.GetString("a_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aticket.
        /// </summary>
        public static string a_ticket {
            get {
                return ResourceManager.GetString("a_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ame.
        /// </summary>
        public static string ame {
            get {
                return ResourceManager.GetString("ame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a announce.
        /// </summary>
        public static string announce {
            get {
                return ResourceManager.GetString("announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a attend.
        /// </summary>
        public static string attend {
            get {
                return ResourceManager.GetString("attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ban.
        /// </summary>
        public static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a breathalyzer.
        /// </summary>
        public static string breathalyzer {
            get {
                return ResourceManager.GetString("breathalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bring.
        /// </summary>
        public static string bring {
            get {
                return ResourceManager.GetString("bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a business.
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a character.
        /// </summary>
        public static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a check.
        /// </summary>
        public static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clearreports.
        /// </summary>
        public static string clear_reports {
            get {
                return ResourceManager.GetString("clear_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a complement.
        /// </summary>
        public static string complement {
            get {
                return ResourceManager.GetString("complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a computer.
        /// </summary>
        public static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a consume.
        /// </summary>
        public static string consume {
            get {
                return ResourceManager.GetString("consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a control.
        /// </summary>
        public static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a coord.
        /// </summary>
        public static string coord {
            get {
                return ResourceManager.GetString("coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cutinterview.
        /// </summary>
        public static string cut_interview {
            get {
                return ResourceManager.GetString("cut_interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deliver.
        /// </summary>
        public static string deliver {
            get {
                return ResourceManager.GetString("deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a die.
        /// </summary>
        public static string die {
            get {
                return ResourceManager.GetString("die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dismiss.
        /// </summary>
        public static string dismiss {
            get {
                return ResourceManager.GetString("dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a door.
        /// </summary>
        public static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a drink.
        /// </summary>
        public static string drink {
            get {
                return ResourceManager.GetString("drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a drivingschool.
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a drop.
        /// </summary>
        public static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a duty.
        /// </summary>
        public static string duty {
            get {
                return ResourceManager.GetString("duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ed.
        /// </summary>
        public static string ed {
            get {
                return ResourceManager.GetString("ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a equipment.
        /// </summary>
        public static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a extract.
        /// </summary>
        public static string extract {
            get {
                return ResourceManager.GetString("extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a f.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fill.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fine.
        /// </summary>
        public static string fine {
            get {
                return ResourceManager.GetString("fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a force.
        /// </summary>
        public static string force {
            get {
                return ResourceManager.GetString("force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fr.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a frequency.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a frisk.
        /// </summary>
        public static string frisk {
            get {
                return ResourceManager.GetString("frisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a furniture.
        /// </summary>
        public static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a garbage.
        /// </summary>
        public static string garbage {
            get {
                return ResourceManager.GetString("garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a give.
        /// </summary>
        public static string give {
            get {
                return ResourceManager.GetString("give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gun.
        /// </summary>
        public static string gun {
            get {
                return ResourceManager.GetString("gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a handcuff.
        /// </summary>
        public static string handcuff {
            get {
                return ResourceManager.GetString("handcuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hang.
        /// </summary>
        public static string hang {
            get {
                return ResourceManager.GetString("hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a heal.
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a health.
        /// </summary>
        public static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hood.
        /// </summary>
        public static string hood {
            get {
                return ResourceManager.GetString("hood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hotwire.
        /// </summary>
        public static string hotwire {
            get {
                return ResourceManager.GetString("hotwire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a house.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a incriminate.
        /// </summary>
        public static string incriminate {
            get {
                return ResourceManager.GetString("incriminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interior.
        /// </summary>
        public static string interior {
            get {
                return ResourceManager.GetString("interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interview.
        /// </summary>
        public static string interview {
            get {
                return ResourceManager.GetString("interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventory.
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jail.
        /// </summary>
        public static string jail {
            get {
                return ResourceManager.GetString("jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a keys.
        /// </summary>
        public static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kick.
        /// </summary>
        public static string kick {
            get {
                return ResourceManager.GetString("kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kickall.
        /// </summary>
        public static string kick_all {
            get {
                return ResourceManager.GetString("kick_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a license.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a licenses.
        /// </summary>
        public static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a locate.
        /// </summary>
        public static string locate {
            get {
                return ResourceManager.GetString("locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a luck.
        /// </summary>
        public static string luck {
            get {
                return ResourceManager.GetString("luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a me.
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a megaphone.
        /// </summary>
        public static string megaphone {
            get {
                return ResourceManager.GetString("megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a n.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ooc.
        /// </summary>
        public static string ooc {
            get {
                return ResourceManager.GetString("ooc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a orders.
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a park.
        /// </summary>
        public static string park {
            get {
                return ResourceManager.GetString("park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a parking.
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pawn.
        /// </summary>
        public static string pawn {
            get {
                return ResourceManager.GetString("pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pay.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pd.
        /// </summary>
        public static string pd {
            get {
                return ResourceManager.GetString("pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pickup.
        /// </summary>
        public static string pick_up {
            get {
                return ResourceManager.GetString("pick_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a plant.
        /// </summary>
        public static string plant {
            get {
                return ResourceManager.GetString("plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a player.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pm.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pos.
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a prize.
        /// </summary>
        public static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a purchase.
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a put.
        /// </summary>
        public static string put {
            get {
                return ResourceManager.GetString("put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a r.
        /// </summary>
        public static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rank.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reanimate.
        /// </summary>
        public static string reanimate {
            get {
                return ResourceManager.GetString("reanimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recoff.
        /// </summary>
        public static string recoff {
            get {
                return ResourceManager.GetString("recoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recon.
        /// </summary>
        public static string recon {
            get {
                return ResourceManager.GetString("recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruit.
        /// </summary>
        public static string recruit {
            get {
                return ResourceManager.GetString("recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a refuel.
        /// </summary>
        public static string refuel {
            get {
                return ResourceManager.GetString("refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reinforces.
        /// </summary>
        public static string reinforces {
            get {
                return ResourceManager.GetString("reinforces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rent.
        /// </summary>
        public static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rentable.
        /// </summary>
        public static string rentable {
            get {
                return ResourceManager.GetString("rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a repaint.
        /// </summary>
        public static string repaint {
            get {
                return ResourceManager.GetString("repaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a repair.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a revive.
        /// </summary>
        public static string revive {
            get {
                return ResourceManager.GetString("revive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a say.
        /// </summary>
        public static string say {
            get {
                return ResourceManager.GetString("say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a scrap.
        /// </summary>
        public static string scrap {
            get {
                return ResourceManager.GetString("scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seatbelt.
        /// </summary>
        public static string seatbelt {
            get {
                return ResourceManager.GetString("seatbelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a silence.
        /// </summary>
        public static string silence {
            get {
                return ResourceManager.GetString("silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a siren.
        /// </summary>
        public static string siren {
            get {
                return ResourceManager.GetString("siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a skin.
        /// </summary>
        public static string skin {
            get {
                return ResourceManager.GetString("skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sms.
        /// </summary>
        public static string sms {
            get {
                return ResourceManager.GetString("sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a speak.
        /// </summary>
        public static string speak {
            get {
                return ResourceManager.GetString("speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a steal.
        /// </summary>
        public static string steal {
            get {
                return ResourceManager.GetString("steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ticket.
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tickets.
        /// </summary>
        public static string tickets {
            get {
                return ResourceManager.GetString("tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a townhall.
        /// </summary>
        public static string town_hall {
            get {
                return ResourceManager.GetString("town_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tp.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trunk.
        /// </summary>
        public static string trunk {
            get {
                return ResourceManager.GetString("trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tunning.
        /// </summary>
        public static string tunning {
            get {
                return ResourceManager.GetString("tunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unpark.
        /// </summary>
        public static string unpark {
            get {
                return ResourceManager.GetString("unpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unrent.
        /// </summary>
        public static string unrent {
            get {
                return ResourceManager.GetString("unrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vehicle.
        /// </summary>
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wardrobe.
        /// </summary>
        public static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weaponsevent.
        /// </summary>
        public static string weapons_event {
            get {
                return ResourceManager.GetString("weapons_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a whisper.
        /// </summary>
        public static string whisper {
            get {
                return ResourceManager.GetString("whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yell.
        /// </summary>
        public static string yell {
            get {
                return ResourceManager.GetString("yell", resourceCulture);
            }
        }
    }
}
