//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.commands.ComRes", typeof(ComRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        public static string _do {
            get {
                return ResourceManager.GetString("do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock.
        /// </summary>
        public static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aduty.
        /// </summary>
        public static string a_duty {
            get {
                return ResourceManager.GetString("a_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aticket.
        /// </summary>
        public static string a_ticket {
            get {
                return ResourceManager.GetString("a_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addpokersit.
        /// </summary>
        public static string addpokersit {
            get {
                return ResourceManager.GetString("addpokersit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ame.
        /// </summary>
        public static string ame {
            get {
                return ResourceManager.GetString("ame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to announce.
        /// </summary>
        public static string announce {
            get {
                return ResourceManager.GetString("announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attend.
        /// </summary>
        public static string attend {
            get {
                return ResourceManager.GetString("attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ban.
        /// </summary>
        public static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breathalyzer.
        /// </summary>
        public static string breathalyzer {
            get {
                return ResourceManager.GetString("breathalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bring.
        /// </summary>
        public static string bring {
            get {
                return ResourceManager.GetString("bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business.
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        public static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearreports.
        /// </summary>
        public static string clear_reports {
            get {
                return ResourceManager.GetString("clear_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complement.
        /// </summary>
        public static string complement {
            get {
                return ResourceManager.GetString("complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer.
        /// </summary>
        public static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consume.
        /// </summary>
        public static string consume {
            get {
                return ResourceManager.GetString("consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to control.
        /// </summary>
        public static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coord.
        /// </summary>
        public static string coord {
            get {
                return ResourceManager.GetString("coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createpokertable.
        /// </summary>
        public static string createpokertable {
            get {
                return ResourceManager.GetString("createpokertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cutinterview.
        /// </summary>
        public static string cut_interview {
            get {
                return ResourceManager.GetString("cut_interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletepokertable.
        /// </summary>
        public static string deletepokertable {
            get {
                return ResourceManager.GetString("deletepokertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deliver.
        /// </summary>
        public static string deliver {
            get {
                return ResourceManager.GetString("deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die.
        /// </summary>
        public static string die {
            get {
                return ResourceManager.GetString("die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dismiss.
        /// </summary>
        public static string dismiss {
            get {
                return ResourceManager.GetString("dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door.
        /// </summary>
        public static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drink.
        /// </summary>
        public static string drink {
            get {
                return ResourceManager.GetString("drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivingschool.
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop.
        /// </summary>
        public static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duty.
        /// </summary>
        public static string duty {
            get {
                return ResourceManager.GetString("duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ed.
        /// </summary>
        public static string ed {
            get {
                return ResourceManager.GetString("ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipment.
        /// </summary>
        public static string equipment {
            get {
                return ResourceManager.GetString("equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extract.
        /// </summary>
        public static string extract {
            get {
                return ResourceManager.GetString("extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fine.
        /// </summary>
        public static string fine {
            get {
                return ResourceManager.GetString("fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to force.
        /// </summary>
        public static string force {
            get {
                return ResourceManager.GetString("force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frequency.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frisk.
        /// </summary>
        public static string frisk {
            get {
                return ResourceManager.GetString("frisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to furniture.
        /// </summary>
        public static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to garbage.
        /// </summary>
        public static string garbage {
            get {
                return ResourceManager.GetString("garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give.
        /// </summary>
        public static string give {
            get {
                return ResourceManager.GetString("give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gun.
        /// </summary>
        public static string gun {
            get {
                return ResourceManager.GetString("gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handcuff.
        /// </summary>
        public static string handcuff {
            get {
                return ResourceManager.GetString("handcuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hang.
        /// </summary>
        public static string hang {
            get {
                return ResourceManager.GetString("hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heal.
        /// </summary>
        public static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to health.
        /// </summary>
        public static string health {
            get {
                return ResourceManager.GetString("health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hood.
        /// </summary>
        public static string hood {
            get {
                return ResourceManager.GetString("hood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotwire.
        /// </summary>
        public static string hotwire {
            get {
                return ResourceManager.GetString("hotwire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to house.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incriminate.
        /// </summary>
        public static string incriminate {
            get {
                return ResourceManager.GetString("incriminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interior.
        /// </summary>
        public static string interior {
            get {
                return ResourceManager.GetString("interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interview.
        /// </summary>
        public static string interview {
            get {
                return ResourceManager.GetString("interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory.
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jail.
        /// </summary>
        public static string jail {
            get {
                return ResourceManager.GetString("jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys.
        /// </summary>
        public static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kick.
        /// </summary>
        public static string kick {
            get {
                return ResourceManager.GetString("kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kickall.
        /// </summary>
        public static string kick_all {
            get {
                return ResourceManager.GetString("kick_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to licenses.
        /// </summary>
        public static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listpokertables.
        /// </summary>
        public static string listpokertables {
            get {
                return ResourceManager.GetString("listpokertables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locate.
        /// </summary>
        public static string locate {
            get {
                return ResourceManager.GetString("locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luck.
        /// </summary>
        public static string luck {
            get {
                return ResourceManager.GetString("luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megaphone.
        /// </summary>
        public static string megaphone {
            get {
                return ResourceManager.GetString("megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ooc.
        /// </summary>
        public static string ooc {
            get {
                return ResourceManager.GetString("ooc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to park.
        /// </summary>
        public static string park {
            get {
                return ResourceManager.GetString("park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parking.
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pawn.
        /// </summary>
        public static string pawn {
            get {
                return ResourceManager.GetString("pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pay.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pd.
        /// </summary>
        public static string pd {
            get {
                return ResourceManager.GetString("pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickup.
        /// </summary>
        public static string pick_up {
            get {
                return ResourceManager.GetString("pick_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant.
        /// </summary>
        public static string plant {
            get {
                return ResourceManager.GetString("plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to player.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pm.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poker.
        /// </summary>
        public static string poker {
            get {
                return ResourceManager.GetString("poker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pos.
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prize.
        /// </summary>
        public static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase.
        /// </summary>
        public static string purchase {
            get {
                return ResourceManager.GetString("purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put.
        /// </summary>
        public static string put {
            get {
                return ResourceManager.GetString("put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reanimate.
        /// </summary>
        public static string reanimate {
            get {
                return ResourceManager.GetString("reanimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recoff.
        /// </summary>
        public static string recoff {
            get {
                return ResourceManager.GetString("recoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recon.
        /// </summary>
        public static string recon {
            get {
                return ResourceManager.GetString("recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recruit.
        /// </summary>
        public static string recruit {
            get {
                return ResourceManager.GetString("recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refuel.
        /// </summary>
        public static string refuel {
            get {
                return ResourceManager.GetString("refuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reinforces.
        /// </summary>
        public static string reinforces {
            get {
                return ResourceManager.GetString("reinforces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removepokersit.
        /// </summary>
        public static string removepokersit {
            get {
                return ResourceManager.GetString("removepokersit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rent.
        /// </summary>
        public static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rentable.
        /// </summary>
        public static string rentable {
            get {
                return ResourceManager.GetString("rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repaint.
        /// </summary>
        public static string repaint {
            get {
                return ResourceManager.GetString("repaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repair.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revive.
        /// </summary>
        public static string revive {
            get {
                return ResourceManager.GetString("revive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say.
        /// </summary>
        public static string say {
            get {
                return ResourceManager.GetString("say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scrap.
        /// </summary>
        public static string scrap {
            get {
                return ResourceManager.GetString("scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seatbelt.
        /// </summary>
        public static string seatbelt {
            get {
                return ResourceManager.GetString("seatbelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silence.
        /// </summary>
        public static string silence {
            get {
                return ResourceManager.GetString("silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siren.
        /// </summary>
        public static string siren {
            get {
                return ResourceManager.GetString("siren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skin.
        /// </summary>
        public static string skin {
            get {
                return ResourceManager.GetString("skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms.
        /// </summary>
        public static string sms {
            get {
                return ResourceManager.GetString("sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speak.
        /// </summary>
        public static string speak {
            get {
                return ResourceManager.GetString("speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steal.
        /// </summary>
        public static string steal {
            get {
                return ResourceManager.GetString("steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket.
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        public static string tickets {
            get {
                return ResourceManager.GetString("tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to townhall.
        /// </summary>
        public static string town_hall {
            get {
                return ResourceManager.GetString("town_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tp.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trunk.
        /// </summary>
        public static string trunk {
            get {
                return ResourceManager.GetString("trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tunning.
        /// </summary>
        public static string tunning {
            get {
                return ResourceManager.GetString("tunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpark.
        /// </summary>
        public static string unpark {
            get {
                return ResourceManager.GetString("unpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrent.
        /// </summary>
        public static string unrent {
            get {
                return ResourceManager.GetString("unrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle.
        /// </summary>
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wardrobe.
        /// </summary>
        public static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weaponsevent.
        /// </summary>
        public static string weapons_event {
            get {
                return ResourceManager.GetString("weapons_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper.
        /// </summary>
        public static string whisper {
            get {
                return ResourceManager.GetString("whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yell.
        /// </summary>
        public static string yell {
            get {
                return ResourceManager.GetString("yell", resourceCulture);
            }
        }
    }
}
