//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.arguments {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArgRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArgRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.arguments.ArgRes", typeof(ArgRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accessory.
        /// </summary>
        public static string accessory {
            get {
                return ResourceManager.GetString("accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ammunition.
        /// </summary>
        public static string ammunition {
            get {
                return ResourceManager.GetString("ammunition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a assault.
        /// </summary>
        public static string assault {
            get {
                return ResourceManager.GetString("assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bag.
        /// </summary>
        public static string bag {
            get {
                return ResourceManager.GetString("bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bahama.
        /// </summary>
        public static string bahama {
            get {
                return ResourceManager.GetString("bahama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bank.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a barrier.
        /// </summary>
        public static string barrier {
            get {
                return ResourceManager.GetString("barrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a basic.
        /// </summary>
        public static string basic {
            get {
                return ResourceManager.GetString("basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a beacon.
        /// </summary>
        public static string beacon {
            get {
                return ResourceManager.GetString("beacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bring.
        /// </summary>
        public static string bring {
            get {
                return ResourceManager.GetString("bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a car.
        /// </summary>
        public static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a chassis.
        /// </summary>
        public static string chassis {
            get {
                return ResourceManager.GetString("chassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cone.
        /// </summary>
        public static string cone {
            get {
                return ResourceManager.GetString("cone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confiscate.
        /// </summary>
        public static string confiscate {
            get {
                return ResourceManager.GetString("confiscate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a consume.
        /// </summary>
        public static string consume {
            get {
                return ResourceManager.GetString("consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dimension.
        /// </summary>
        public static string dimension {
            get {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a doors.
        /// </summary>
        public static string doors {
            get {
                return ResourceManager.GetString("doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a drop.
        /// </summary>
        public static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a earrings.
        /// </summary>
        public static string earrings {
            get {
                return ResourceManager.GetString("earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a electronics.
        /// </summary>
        public static string electronics {
            get {
                return ResourceManager.GetString("electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a equip.
        /// </summary>
        public static string equip {
            get {
                return ResourceManager.GetString("equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a faction.
        /// </summary>
        public static string faction {
            get {
                return ResourceManager.GetString("faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fish.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a garbage.
        /// </summary>
        public static string garbage {
            get {
                return ResourceManager.GetString("garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gas.
        /// </summary>
        public static string gas {
            get {
                return ResourceManager.GetString("gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a give.
        /// </summary>
        public static string give {
            get {
                return ResourceManager.GetString("give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a glasses.
        /// </summary>
        public static string glasses {
            get {
                return ResourceManager.GetString("glasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hat.
        /// </summary>
        public static string hat {
            get {
                return ResourceManager.GetString("hat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hospital.
        /// </summary>
        public static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a house.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a identification.
        /// </summary>
        public static string identification {
            get {
                return ResourceManager.GetString("identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inner.
        /// </summary>
        public static string inner {
            get {
                return ResourceManager.GetString("inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insurance.
        /// </summary>
        public static string insurance {
            get {
                return ResourceManager.GetString("insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interior.
        /// </summary>
        public static string interior {
            get {
                return ResourceManager.GetString("interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a interview.
        /// </summary>
        public static string interview {
            get {
                return ResourceManager.GetString("interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a leave.
        /// </summary>
        public static string leave {
            get {
                return ResourceManager.GetString("leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lend.
        /// </summary>
        public static string lend {
            get {
                return ResourceManager.GetString("lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a license.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a licenses.
        /// </summary>
        public static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lock.
        /// </summary>
        public static string lock_command {
            get {
                return ResourceManager.GetString("lock_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a machinegun.
        /// </summary>
        public static string machinegun {
            get {
                return ResourceManager.GetString("machinegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mark.
        /// </summary>
        public static string mark {
            get {
                return ResourceManager.GetString("mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mask.
        /// </summary>
        public static string mask {
            get {
                return ResourceManager.GetString("mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mechanic.
        /// </summary>
        public static string mechanic {
            get {
                return ResourceManager.GetString("mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a modify.
        /// </summary>
        public static string modify {
            get {
                return ResourceManager.GetString("modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a money.
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a motorcycle.
        /// </summary>
        public static string motorcycle {
            get {
                return ResourceManager.GetString("motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a move.
        /// </summary>
        public static string move {
            get {
                return ResourceManager.GetString("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a news.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oral.
        /// </summary>
        public static string oral {
            get {
                return ResourceManager.GetString("oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a outer.
        /// </summary>
        public static string outer {
            get {
                return ResourceManager.GetString("outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a owner.
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pickup.
        /// </summary>
        public static string pick_up {
            get {
                return ResourceManager.GetString("pick_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pistol.
        /// </summary>
        public static string pistol {
            get {
                return ResourceManager.GetString("pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a place.
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a places.
        /// </summary>
        public static string places {
            get {
                return ResourceManager.GetString("places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a police.
        /// </summary>
        public static string police {
            get {
                return ResourceManager.GetString("police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rank.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rename.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rent.
        /// </summary>
        public static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a repaint.
        /// </summary>
        public static string repaint {
            get {
                return ResourceManager.GetString("repaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a repair.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a revolver.
        /// </summary>
        public static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a see.
        /// </summary>
        public static string see {
            get {
                return ResourceManager.GetString("see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a set.
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sex.
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shotgun.
        /// </summary>
        public static string shotgun {
            get {
                return ResourceManager.GetString("shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sms.
        /// </summary>
        public static string sms {
            get {
                return ResourceManager.GetString("sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sniper.
        /// </summary>
        public static string sniper {
            get {
                return ResourceManager.GetString("sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spikes.
        /// </summary>
        public static string spikes {
            get {
                return ResourceManager.GetString("spikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a state.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a statehouse.
        /// </summary>
        public static string statehouse {
            get {
                return ResourceManager.GetString("statehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a townhall.
        /// </summary>
        public static string townhall {
            get {
                return ResourceManager.GetString("townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tp.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tyres.
        /// </summary>
        public static string tyres {
            get {
                return ResourceManager.GetString("tyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vanilla.
        /// </summary>
        public static string vanilla {
            get {
                return ResourceManager.GetString("vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vehicle.
        /// </summary>
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a view.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weapon.
        /// </summary>
        public static string weapon {
            get {
                return ResourceManager.GetString("weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wear.
        /// </summary>
        public static string wear {
            get {
                return ResourceManager.GetString("wear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a windows.
        /// </summary>
        public static string windows {
            get {
                return ResourceManager.GetString("windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a withdraw.
        /// </summary>
        public static string withdraw {
            get {
                return ResourceManager.GetString("withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workshop.
        /// </summary>
        public static string workshop {
            get {
                return ResourceManager.GetString("workshop", resourceCulture);
            }
        }
    }
}
