//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.general {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.general.GenRes", typeof(GenRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [STAFF NOTIFICATION] .
        /// </summary>
        public static string admin_notice {
            get {
                return ResourceManager.GetString("admin_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age: .
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ammunation.
        /// </summary>
        public static string ammunation {
            get {
                return ResourceManager.GetString("ammunation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [ANNOUNCEMENT] .
        /// </summary>
        public static string announcement {
            get {
                return ResourceManager.GetString("announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a status: attended by .
        /// </summary>
        public static string attended_by {
            get {
                return ResourceManager.GetString("attended_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available types: {0}.
        /// </summary>
        public static string available_types {
            get {
                return ResourceManager.GetString("available_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank: .
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank interest: .
        /// </summary>
        public static string bank_interest {
            get {
                return ResourceManager.GetString("bank_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deposit.
        /// </summary>
        public static string bank_op_deposit {
            get {
                return ResourceManager.GetString("bank_op_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transfer.
        /// </summary>
        public static string bank_op_transfer {
            get {
                return ResourceManager.GetString("bank_op_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Withdraw.
        /// </summary>
        public static string bank_op_withdraw {
            get {
                return ResourceManager.GetString("bank_op_withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bar.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Barber shop.
        /// </summary>
        public static string barber_shop {
            get {
                return ResourceManager.GetString("barber_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Benny&apos;s workshop.
        /// </summary>
        public static string benny_workshop {
            get {
                return ResourceManager.GetString("benny_workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boat dealer.
        /// </summary>
        public static string boat_dealer {
            get {
                return ResourceManager.GetString("boat_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business.
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a __________Information about business with ID {0}__________.
        /// </summary>
        public static string business_check_title {
            get {
                return ResourceManager.GetString("business_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Car dealer.
        /// </summary>
        public static string car_dealer {
            get {
                return ResourceManager.GetString("car_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash factory.
        /// </summary>
        public static string cash_factory {
            get {
                return ResourceManager.GetString("cash_factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the command above to see the vehicle list.
        /// </summary>
        public static string catalog_help {
            get {
                return ResourceManager.GetString("catalog_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press F to change your character.
        /// </summary>
        public static string character_help {
            get {
                return ResourceManager.GetString("character_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  at phone: .
        /// </summary>
        public static string chat_phone {
            get {
                return ResourceManager.GetString("chat_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  at radio: .
        /// </summary>
        public static string chat_radio {
            get {
                return ResourceManager.GetString("chat_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  says: .
        /// </summary>
        public static string chat_say {
            get {
                return ResourceManager.GetString("chat_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  whispers: .
        /// </summary>
        public static string chat_whisper {
            get {
                return ResourceManager.GetString("chat_whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  yells: .
        /// </summary>
        public static string chat_yell {
            get {
                return ResourceManager.GetString("chat_yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clothes store.
        /// </summary>
        public static string clothes {
            get {
                return ResourceManager.GetString("clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clubhouse type 1.
        /// </summary>
        public static string clubhouse_first {
            get {
                return ResourceManager.GetString("clubhouse_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clubhouse type 2.
        /// </summary>
        public static string clubhouse_second {
            get {
                return ResourceManager.GetString("clubhouse_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cocaine lab.
        /// </summary>
        public static string cocaine_lab {
            get {
                return ResourceManager.GetString("cocaine_lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a command_used {0} {1} {2}.
        /// </summary>
        public static string command_used {
            get {
                return ResourceManager.GetString("command_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disco.
        /// </summary>
        public static string disco {
            get {
                return ResourceManager.GetString("disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document office.
        /// </summary>
        public static string document_office {
            get {
                return ResourceManager.GetString("document_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driving school.
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electronic&apos;s  store.
        /// </summary>
        public static string electronics {
            get {
                return ResourceManager.GetString("electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergency medical services.
        /// </summary>
        public static string emergency_faction {
            get {
                return ResourceManager.GetString("emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the command above to get the police equipment.
        /// </summary>
        public static string equipment_help {
            get {
                return ResourceManager.GetString("equipment_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiry date: .
        /// </summary>
        public static string expiry {
            get {
                return ResourceManager.GetString("expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extra income: .
        /// </summary>
        public static string extra_income {
            get {
                return ResourceManager.GetString("extra_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faction: .
        /// </summary>
        public static string faction {
            get {
                return ResourceManager.GetString("faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMS.
        /// </summary>
        public static string faction_ems {
            get {
                return ResourceManager.GetString("faction_ems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LSPD.
        /// </summary>
        public static string faction_lspd {
            get {
                return ResourceManager.GetString("faction_lspd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string faction_news {
            get {
                return ResourceManager.GetString("faction_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Town hall.
        /// </summary>
        public static string faction_townhall {
            get {
                return ResourceManager.GetString("faction_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport service.
        /// </summary>
        public static string faction_transport {
            get {
                return ResourceManager.GetString("faction_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factory.
        /// </summary>
        public static string factory {
            get {
                return ResourceManager.GetString("factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fastfood deliverer job.
        /// </summary>
        public static string fastfood_job {
            get {
                return ResourceManager.GetString("fastfood_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment of fines.
        /// </summary>
        public static string fines_payment {
            get {
                return ResourceManager.GetString("fines_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fishing store.
        /// </summary>
        public static string fishing {
            get {
                return ResourceManager.GetString("fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garage.
        /// </summary>
        public static string garage {
            get {
                return ResourceManager.GetString("garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garage low end.
        /// </summary>
        public static string garage_low_end {
            get {
                return ResourceManager.GetString("garage_low_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garbage man job.
        /// </summary>
        public static string garbage_job {
            get {
                return ResourceManager.GetString("garbage_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas station.
        /// </summary>
        public static string gas_station {
            get {
                return ResourceManager.GetString("gas_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest .
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hardware store.
        /// </summary>
        public static string hardware {
            get {
                return ResourceManager.GetString("hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use ~b~/help ~w~command whenever you want to get general information..
        /// </summary>
        public static string help_hint {
            get {
                return ResourceManager.GetString("help_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hooker service.
        /// </summary>
        public static string hooker {
            get {
                return ResourceManager.GetString("hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospital.
        /// </summary>
        public static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a __________Information about house with ID {0}__________.
        /// </summary>
        public static string house_check_title {
            get {
                return ResourceManager.GetString("house_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House sale.
        /// </summary>
        public static string house_sale {
            get {
                return ResourceManager.GetString("house_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House taxes from .
        /// </summary>
        public static string house_taxes_from {
            get {
                return ResourceManager.GetString("house_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Houses: .
        /// </summary>
        public static string houses {
            get {
                return ResourceManager.GetString("houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identification card.
        /// </summary>
        public static string identification {
            get {
                return ResourceManager.GetString("identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interior.
        /// </summary>
        public static string interior {
            get {
                return ResourceManager.GetString("interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interviewer .
        /// </summary>
        public static string interviewer {
            get {
                return ResourceManager.GetString("interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IPL: .
        /// </summary>
        public static string ipl {
            get {
                return ResourceManager.GetString("ipl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jewelry.
        /// </summary>
        public static string jewelry {
            get {
                return ResourceManager.GetString("jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job: .
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the command above to get more information about the job.
        /// </summary>
        public static string job_help {
            get {
                return ResourceManager.GetString("job_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lent vehicles: .
        /// </summary>
        public static string lent_vehicles {
            get {
                return ResourceManager.GetString("lent_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supermarket.
        /// </summary>
        public static string market {
            get {
                return ResourceManager.GetString("market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanic.
        /// </summary>
        public static string mechanic {
            get {
                return ResourceManager.GetString("mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanic job.
        /// </summary>
        public static string mechanic_job {
            get {
                return ResourceManager.GetString("mechanic_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medical insurance.
        /// </summary>
        public static string medical_insurance {
            get {
                return ResourceManager.GetString("medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online members:.
        /// </summary>
        public static string members_online {
            get {
                return ResourceManager.GetString("members_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta lab.
        /// </summary>
        public static string meta_lab {
            get {
                return ResourceManager.GetString("meta_lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Money: .
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motorcycle dealer.
        /// </summary>
        public static string motorcycle_dealer {
            get {
                return ResourceManager.GetString("motorcycle_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplier: .
        /// </summary>
        public static string multiplier {
            get {
                return ResourceManager.GetString("multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name: .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News announcement.
        /// </summary>
        public static string news_announce {
            get {
                return ResourceManager.GetString("news_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string news_faction {
            get {
                return ResourceManager.GetString("news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News prize.
        /// </summary>
        public static string news_prize {
            get {
                return ResourceManager.GetString("news_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No faction.
        /// </summary>
        public static string no_faction {
            get {
                return ResourceManager.GetString("no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No rank.
        /// </summary>
        public static string no_rank {
            get {
                return ResourceManager.GetString("no_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s no pending report to attend..
        /// </summary>
        public static string not_faction_warning {
            get {
                return ResourceManager.GetString("not_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owned vehicles: .
        /// </summary>
        public static string owned_vehicles {
            get {
                return ResourceManager.GetString("owned_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner: .
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pawn shop.
        /// </summary>
        public static string pawn_shop {
            get {
                return ResourceManager.GetString("pawn_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment between players.
        /// </summary>
        public static string payment_players {
            get {
                return ResourceManager.GetString("payment_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Phone] .
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a place: .
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Played: .
        /// </summary>
        public static string played_time {
            get {
                return ResourceManager.GetString("played_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private message from .
        /// </summary>
        public static string pm_from {
            get {
                return ResourceManager.GetString("pm_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private message to .
        /// </summary>
        public static string pm_to {
            get {
                return ResourceManager.GetString("pm_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Police depot.
        /// </summary>
        public static string police_depot {
            get {
                return ResourceManager.GetString("police_depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Police department.
        /// </summary>
        public static string police_faction {
            get {
                return ResourceManager.GetString("police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Police station.
        /// </summary>
        public static string police_station {
            get {
                return ResourceManager.GetString("police_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: .
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private office.
        /// </summary>
        public static string private_office {
            get {
                return ResourceManager.GetString("private_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products: .
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public parking.
        /// </summary>
        public static string public_parking {
            get {
                return ResourceManager.GetString("public_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Radio] .
        /// </summary>
        public static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rank: .
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergency reports:.
        /// </summary>
        public static string reports_header {
            get {
                return ResourceManager.GetString("reports_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role points: .
        /// </summary>
        public static string role_points {
            get {
                return ResourceManager.GetString("role_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve been assigned east route..
        /// </summary>
        public static string route_east {
            get {
                return ResourceManager.GetString("route_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve been assigned north route..
        /// </summary>
        public static string route_north {
            get {
                return ResourceManager.GetString("route_north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve been assigned south route..
        /// </summary>
        public static string route_south {
            get {
                return ResourceManager.GetString("route_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve been assigned west route..
        /// </summary>
        public static string route_west {
            get {
                return ResourceManager.GetString("route_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salary: .
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrapyard.
        /// </summary>
        public static string scrapyard {
            get {
                return ResourceManager.GetString("scrapyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sex: .
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sherif Faction.
        /// </summary>
        public static string sheriff_faction {
            get {
                return ResourceManager.GetString("sheriff_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slaughterhouse.
        /// </summary>
        public static string slaughterhouse {
            get {
                return ResourceManager.GetString("slaughterhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMS from .
        /// </summary>
        public static string sms_from {
            get {
                return ResourceManager.GetString("sms_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The state.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House state: Occupied.
        /// </summary>
        public static string state_occupied {
            get {
                return ResourceManager.GetString("state_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House state: For rent.
        /// </summary>
        public static string state_rent {
            get {
                return ResourceManager.GetString("state_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House state: For sale.
        /// </summary>
        public static string state_sale {
            get {
                return ResourceManager.GetString("state_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status: .
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tattoo shop.
        /// </summary>
        public static string tattoo_shop {
            get {
                return ResourceManager.GetString("tattoo_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taxi license.
        /// </summary>
        public static string taxi_license {
            get {
                return ResourceManager.GetString("taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Lost clubhouse.
        /// </summary>
        public static string the_lost {
            get {
                return ResourceManager.GetString("the_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a thief_job.
        /// </summary>
        public static string thief_job {
            get {
                return ResourceManager.GetString("thief_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use ~b~/ticket ~w~command to ask for help from the staff..
        /// </summary>
        public static string ticket_hint {
            get {
                return ResourceManager.GetString("ticket_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time: .
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torture room.
        /// </summary>
        public static string torture_room {
            get {
                return ResourceManager.GetString("torture_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Town hall.
        /// </summary>
        public static string townhall {
            get {
                return ResourceManager.GetString("townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Town hall.
        /// </summary>
        public static string townhall_faction {
            get {
                return ResourceManager.GetString("townhall_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the command above to get the available formalities.
        /// </summary>
        public static string townhall_help {
            get {
                return ResourceManager.GetString("townhall_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport services.
        /// </summary>
        public static string transport_faction {
            get {
                return ResourceManager.GetString("transport_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trucker_job.
        /// </summary>
        public static string trucker_job {
            get {
                return ResourceManager.GetString("trucker_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a status: unattended.
        /// </summary>
        public static string unattended {
            get {
                return ResourceManager.GetString("unattended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unemployed.
        /// </summary>
        public static string unemployed {
            get {
                return ResourceManager.GetString("unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vanilla Unicorn.
        /// </summary>
        public static string vanilla {
            get {
                return ResourceManager.GetString("vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _________Information about vehicle with ID {0}_________.
        /// </summary>
        public static string vehicle_check_title {
            get {
                return ResourceManager.GetString("vehicle_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model: .
        /// </summary>
        public static string vehicle_model {
            get {
                return ResourceManager.GetString("vehicle_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plate: .
        /// </summary>
        public static string vehicle_plate {
            get {
                return ResourceManager.GetString("vehicle_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle sale.
        /// </summary>
        public static string vehicle_sale {
            get {
                return ResourceManager.GetString("vehicle_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taxes from .
        /// </summary>
        public static string vehicle_taxes_from {
            get {
                return ResourceManager.GetString("vehicle_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle warehouse.
        /// </summary>
        public static string vehicle_warehouse {
            get {
                return ResourceManager.GetString("vehicle_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse.
        /// </summary>
        public static string warehouse {
            get {
                return ResourceManager.GetString("warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse large.
        /// </summary>
        public static string warehouse_large {
            get {
                return ResourceManager.GetString("warehouse_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse medium.
        /// </summary>
        public static string warehouse_medium {
            get {
                return ResourceManager.GetString("warehouse_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse small.
        /// </summary>
        public static string warehouse_small {
            get {
                return ResourceManager.GetString("warehouse_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weapon crate.
        /// </summary>
        public static string weapon_crate {
            get {
                return ResourceManager.GetString("weapon_crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string weazel_news {
            get {
                return ResourceManager.GetString("weazel_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weed warehouse.
        /// </summary>
        public static string weed_warehouse {
            get {
                return ResourceManager.GetString("weed_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use ~b~/welcome ~w~command in order to know how can you start your life in Los Santos..
        /// </summary>
        public static string welcome_hint {
            get {
                return ResourceManager.GetString("welcome_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to WiredPlayers, {0}..
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
